; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:Waveshare_touch_lcd_4x4]
platform = espressif32
board = esp32s3box
framework = arduino
monitor_speed = 115200

board_upload.flash_size = 16MB
; change microcontroller
board_build.mcu = esp32s3
; change MCU frequency
board_build.f_cpu = 240000000L

board_build.arduino.memory_type = qio_opi
board_build.f_flash = 80000000L
board_build.flash_mode = qio

lib_deps :
    lvgl/lvgl @ 8.4.0
    moononournation/GFX Library for Arduino @ 1.6.5
    lewisxhe/SensorLib @ 0.4.0

build_flags =
    -I ui
    -D LV_CONF_PATH="${PROJECT_DIR}/include/lv_conf.h"
    
